image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
configuration:
  - Debug
before_build:
  - cmd: nuget install NUnit.Console -Version 3.7.0 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install opencover.portable
  - cmd: choco install codecov
build:
  project: Uml.sln
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion
after_test:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\Uml.Tests\Uml.Tests.csproj" -filter:"+[Uml*]* +[Implementation*]* -[Uml.Tests*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:"coverage.xml"
  - codecov -f "coverage.xml" -t e3c3528a-7d37-4d0d-a9f6-59c3d9b6cc0e